server:
  port: 8081
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
spring:
  rabbitmq:
    host: 192.168.239.100 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: admin
    password: 123
    virtual-host: /
    #做消息可靠性
    publisher-confirm-type: correlated
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 # 最大重试次数

  application:
    name: keyuan
  redis:
    host: 192.168.239.100
    port: 6380
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: '1234'
      username: root
      url: jdbc:mysql://192.168.239.100:3306/keyuan2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      jackson:
        default-property-inclusion: non_null #  #不为空的属性才会序列化,具体属性可看JsonInclude.Include
      type: com.alibaba.druid.pool.DruidDataSource


  #别名类
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.keyuan.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pageHelp的配置
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

logging:
  #日志的等级
  level:
    keyuan: debug




